version: '3.1'
services:
    db1:
        image: cockroachdb/cockroach:v1.1.1
        deploy:
            mode: replicated
            replicas: 1
        ports:
            - 8888:8080
            - 26257:26257
        command: start --advertise-host=cockroach_db1 --logtostderr --insecure
        networks:
            - cockroachdb
        volumes:
            - cockroachdb-1:/cockroach/cockroach-data

    db2:
        image: cockroachdb/cockroach:v1.1.1
        deploy:
            mode: replicated
            replicas: 1
        command: start --advertise-host=cockroach_db2 --join=cockroach_db1:26257 --logtostderr --insecure
        networks:
            - cockroachdb
        volumes:
            - cockroachdb-2:/cockroach/cockroach-data

    db3:
        image: cockroachdb/cockroach:v1.1.1
        deploy:
            mode: replicated
            replicas: 1
        command: start --advertise-host=cockroach_db3 --join=cockroach_db1:26257 --logtostderr --insecure
        networks:
            - cockroachdb
        volumes:
            - cockroachdb-3:/cockroach/cockroach-data

    main:
        image: dockersamples/visualizer
        ports:
          - ${HTTP_PORT:-8080}:8080
        networks:
          - cockroachdb
        deploy:
          placement:
            constraints: [node.role == manager]
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          
    crdb-proxy:
        image: haproxy
        ports:
          - 26258:26257
        volumes:
            - ./configs/haproxy:/usr/local/etc/haproxy:ro
        networks:
          - cockroachdb
        deploy:
          mode: replicated
          replicas: 1
          update_config:
            parallelism: 1
            delay: 2m
          
    prometheus:
        image: prom/prometheus
        ports:
          - "9090"
        networks:
          - cockroachdb
        volumes:
            - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
        command: --config.file=/etc/prometheus/prometheus.yml --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles
        deploy:
          mode: replicated
          replicas: 1
          resources:
            limits:
              cpus: '0.50'
              memory: 1024M
            reservations:
              cpus: '0.50'
              memory: 128M
          
    # cadvisor global service
    cadvisor:
        image: google/cadvisor
        hostname: '{{.Node.ID}}'
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
          - /var/run/docker.sock:/var/run/docker.sock:ro
        deploy:
          mode: global
          resources:
            limits:
              cpus: '0.10'
              memory: 128M
            reservations:
              cpus: '0.10'
              memory: 64M
        networks:
          - cockroachdb
          
          
    node-exporter:
        image: prom/node-exporter
        networks:
          - cockroachdb
        volumes:
          - /proc:/host/proc
          - /sys:/host/sys
          - /:/rootfs
          - /etc/hostname:/etc/host_hostname
        hostname: "{{.Node.ID}}"
        environment:
          HOST_HOSTNAME: /etc/host_hostname
        command: --path.procfs /host/proc --path.sysfs /host/sys --collector.textfile.directory /etc/node-exporter/ --collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)"
        deploy:
          mode: global
          resources:
            limits:
              cpus: '0.10'
              memory: 32M
            reservations:
              cpus: '0.10'
              memory: 16M
    # grafana service
    grafana:
        image: grafana/grafana
        ports:
          - "3000:3000"
        networks:
          - cockroachdb
        environment:
          GF_SECURITY_ADMIN_PASSWORD: ${GF_PASSWORD:-admin}
          PROMETHEUS_ENDPOINT: http://prometheus:9090
        deploy:
          mode: replicated
          replicas: 1
          resources:
            limits:
              cpus: '0.50'
              memory: 64M
            reservations:
              cpus: '0.50'
              memory: 32M

networks:
    cockroachdb:
        external: true

volumes:
    cockroachdb-1:
    cockroachdb-2:
    cockroachdb-3: