# Prometheus configuration for cockroach clusters.
#
# Run with:
# $ prometheus -config.file=prometheus.yml
global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - "rules/alerts.rules"
  - "rules/aggregation.rules"

scrape_configs:
  - job_name: 'prometheus'
    dns_sd_configs:
    - names:
      - 'tasks.prometheus'
      type: 'A'
      port: 9090

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'docker-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.docker-exporter'
      type: 'A'
      port: 4999

  - job_name: 'cockroach'
    metrics_path: '/_status/vars'
    scheme: 'http'

    tls_config:
      insecure_skip_verify: true

    static_configs:
    - targets: ['db1:8080', 'db2:8080', 'db3:8080']
      labels:
        cluster: 'cockroachdb-cluster'